### ISSUE TITLE
Numbers in availability bar

### ISSUE THREAD

**Issue by Nachtgarm** [bigcartel-themes/sidecar#103]
Hi. I'd like to know how to display numbers instead of percentage in the availability bar for this theme. 
```
#product_inventory .bar span em {
  display: block;
}
```
as suggested for the Luna Theme is not working for the Sidecar theme, or am I missing smth.? 

Thanks in advance.

**Comment by nickendle** [comment]
You'll need to edit the Product page HTML to show quantities instead of percentages. Find this code near the bottom:

```
{% if option.sold_out %}
  Sold Out
{% else %}
  {{ option.inventory }}%
{% endif %}
```

Replace `{{ option.inventory }}%` with something like `{{ option.quantity }} in stock` and you'll be all set!

**Comment by Nachtgarm** [comment]
That's what I was looking for. Thank you
