### ISSUE TITLE
constrain home / products images to appropriate dimensions

### ISSUE THREAD

**Issue by nickendle** [bigcartel-themes/sidecar#97]

**Comment by rachgo** [comment]
Not sure if this is the same issue, but a few folks have asked about how to make their thumbnails 'sharper on the responsive version, if they're using small/medium thumbnail settings. 

I've been suggesting they either bump up to large thumbnails, or set a specific constrain value, like 600, and that usually fixes it to their liking. Would that be something we could change in the theme itself, esp. for folks on the Gold plan?

(default theme on left, constrained on the right)

![untitled](https://cloud.githubusercontent.com/assets/3578349/7521328/a4dd9366-f4b2-11e4-8fff-11583b9493f1.jpg)
